name: Ejecutar Scraper UCE

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      REDMINE_USER: ${{ secrets.REDMINE_USER }}
      REDMINE_PASS: ${{ secrets.REDMINE_PASS }}

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r scraper/requirements.txt

      - name: Ejecutar scraper
        run: |
          python scraper/estadoTorres.py

      - name: Evitar commit vacío
        run: |
          if git diff --quiet; then
            echo "No hay cambios, no commit."
            exit 0
          fi
          
      - name: Guardar cambios
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          # Traer cambios remotos, pero ignorar conflictos en json autogenerados
          git fetch origin main
          git reset --soft origin/main

          git add datos_issue.json log_scraper.json || true

          if git diff --cached --quiet; then
            echo "No hay cambios para commitear."
            exit 0
          fi

          git commit -m "Auto actualización $(date)"
          git push
