name: Ejecutar Scraper UCE

on:
  schedule:
    - cron: "*/5 * * * *"   # cada 5 minutos
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r scraper/requirements.txt

      - name: Ejecutar scraper
        run: |
          python scraper/estadoTorres.py

      - name: Guardar cambios
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add datos_issue.json log_scraper.json || true
          git commit -m "Actualización automática $(date)" || echo "No hay cambios para subir"
          git push
